order_requests = {
    "sample_coupon_order": {
        "tVer": "1.0.0",
        "order_id": 61124111,
        "store_id": 3282,
        "vendor_store_id": "",
        "store_name": "Lombardi’s Pizza",
        "service_type": "takeout",
        "submitted_date": "2026-03-07T01:11:00-0500",
        "print_date": "2026-03-07T01:11:00-0500",
        "deferred_date": "",
        "misc_charges": [
            {
                "misc_charge_name": "delivery_charge",
                "misc_charge_desc": "Delivery Fee",
                "misc_charge_amount": 4,
            },
            {
                "misc_charge_name": "other_charge",
                "misc_charge_desc": "Service Charge",
                "misc_charge_amount": 0.5,
            },
        ],
        "tip": 3.02,
        "taxes": [{"tax_name": "Sales Tax", "tax_amount": 1.81}],
        "is_tax_exempt": False,
        "order_total": 35.05,
        "balance_owing": 0,
        "notes": "",
        "customer": {
            "first_name": "ERIK",
            "last_name": "DAVIS",
            "company": "",
            "phone": "4432077156",
            "ext": "",
            "email": "ERIK_TAILS11@YAHOO.COM",
        },
        "payments": [
            {
                "type": "JCB",
                "amount": 35.05,
                "card_number": "xxxxxxxxxxxxx303",
                "card_holder": "ERIK DAIVS",
                "auth_code": "052482",
                "transaction_id": "",
                "token": "",
            }
        ],
        "items": [
            {
                "name": "Regular Tomato  Cheese Pizza",
                "size_id": 2,
                "size_name": "12 Medium",
                "quantity": 1,
                "price": 9.99,
                "plu": "",
                "who": "",
                "group_id": "",
                "notes": "",
                "modifiers": [
                    {
                        "side": "whole",
                        "name": "Add Pineapple",
                        "quantity": 1,
                        "plu": "",
                        "price": 1.5,
                        "action": "add",
                    }
                ],
            },
            {
                "name": "Regular Tomato  Cheese Pizza",
                "size_id": 3,
                "size_name": "14 Large",
                "quantity": 1,
                "price": 11.99,
                "plu": "",
                "who": "",
                "group_id": "",
                "notes": "",
                "modifiers": [
                    {
                        "side": "whole",
                        "name": "Add Double Cheese",
                        "quantity": 1,
                        "plu": "",
                        "price": 1.75,
                        "action": "add",
                    }
                ],
            },
            {
                "name": "Brownies",
                "size_id": 1,
                "size_name": "Serving",
                "quantity": 1,
                "price": 4.49,
                "plu": "",
                "who": "",
                "group_id": "",
                "notes": "",
                "modifiers": [],
            },
        ],
        "coupons": None,
    },
    "sample_delayed_order": {
        "tVer": "1.0.0",
        "order_id": 61124127,
        "store_id": 3282,
        "vendor_store_id": "",
        "store_name": "Lombardi’s Pizza",
        "service_type": "takeout",
        "submitted_date": "2026-03-07T01:19:00-0500",
        "print_date": "2026-03-16T13:10:00-0400",
        "deferred_date": "2026-03-16T14:10:00-0400",
        "misc_charges": [
            {
                "misc_charge_name": "delivery_charge",
                "misc_charge_desc": "Delivery Fee",
                "misc_charge_amount": 4,
            },
            {
                "misc_charge_name": "other_charge",
                "misc_charge_desc": "Service Charge",
                "misc_charge_amount": 0.5,
            },
        ],
        "tip": 0,
        "taxes": [{"tax_name": "Sales Tax", "tax_amount": 0.39}],
        "is_tax_exempt": False,
        "order_total": 6.88,
        "balance_owing": 6.88,
        "notes": "",
        "customer": {
            "first_name": "AARYAN",
            "last_name": "DHAKAL",
            "company": "",
            "phone": "6674030865",
            "ext": "",
            "email": "AARYAN.DHAKAL22@GMAIL.COM",
        },
        "payments": None,
        "items": [
            {
                "name": "Mozzarella Sticks",
                "size_id": 1,
                "size_name": "6 Piece",
                "quantity": 1,
                "price": 5.99,
                "plu": "",
                "who": "",
                "group_id": "",
                "notes": "",
                "modifiers": [],
            }
        ],
        "coupons": None,
    },
    "sample_real_order": {
        "tVer": "1.0.0",
        "order_id": 61107760,
        "store_id": 3282,
        "vendor_store_id": "",
        "store_name": "Lombardi’s Pizza",
        "service_type": "takeout",
        "submitted_date": "2026-03-06T12:51:00-0500",
        "print_date": "2026-03-06T12:51:00-0500",
        "misc_charges": [
            {
                "misc_charge_name": "other_charge",
                "misc_charge_desc": "Service Charge",
                "misc_charge_amount": 0.5,
            }
        ],
        "taxes": [{"tax_name": "Sales Tax", "tax_amount": 0.11}],
        "is_tax_exempt": False,
        "order_total": 1.86,
        "balance_owing": 1.86,
        "notes": "test",
        "customer": {
            "first_name": "BEN",
            "last_name": "MANSURIQ",
            "company": "",
            "phone": "6046487389",
            "ext": "",
            "email": "BENJAMIN.MANSURI@BRYGID.COM",
        },
        "items": [
            {
                "name": "12 oz Soda",
                "size_id": 1,
                "size_name": "Serving",
                "quantity": 1,
                "price": 1.25,
                "plu": "",
                "who": "",
                "group_id": "",
                "notes": "",
                "modifiers": [
                    {
                        "side": "whole",
                        "name": "Coke",
                        "quantity": 1,
                        "plu": "",
                        "price": 0.0,
                        "action": "add",
                    }
                ],
            }
        ],
    },
    "basic_pickup_order": {
        "tVer": "1.0",
        "order_id": 1001,
        "store_id": 90001,
        "vendor_store_id": "BRY-001",
        "store_name": "Brygid Pizza",
        "service_type": "pickup",
        "submitted_date": "2026-02-07T10:15:00Z",
        "print_date": "2026-02-07T10:16:00Z",
        "deferred_date": "",
        "misc_charges": [],
        "tip": 2.50,
        "taxes": [{"tax_name": "Sales Tax", "tax_amount": 1.75}],
        "is_tax_exempt": False,
        "order_total": 18.25,
        "balance_owing": 0.00,
        "notes": "Extra napkins please",
        "customer": {
            "first_name": "John",
            "last_name": "Doe",
            "company": "",
            "phone": "5551234567",
            "ext": "",
            "email": "john.doe@example.com",
        },
        "delivery_address": None,
        "delivery_provider": None,
        "payments": [
            {
                "type": "card",
                "amount": 18.25,
                "card_number": "**** **** **** 4242",
                "card_holder": "John Doe",
                "auth_code": "AUTH123",
                "transaction_id": "TXN1001",
                "token": "tok_abc123",
            }
        ],
        "items": [
            {
                "name": "Margherita Pizza",
                "size_id": 2,
                "size_name": "Medium",
                "quantity": 1,
                "price": 14.00,
                "plu": "PZ100",
                "who": "Kitchen",
                "group_id": "pizza",
                "notes": "",
                "modifiers": [],
            }
        ],
        "coupons": [],
    },
    "delivery_with_address": {
        "tVer": "1.0",
        "order_id": 1002,
        "store_id": 90001,
        "vendor_store_id": "BRY-001",
        "store_name": "Brygid Pizza",
        "service_type": "delivery",
        "submitted_date": "2026-02-07T11:00:00Z",
        "print_date": "2026-02-07T11:01:00Z",
        "deferred_date": "",
        "misc_charges": [
            {
                "misc_charge_name": "Delivery Fee",
                "misc_charge_desc": "Standard delivery",
                "misc_charge_amount": 3.99,
            }
        ],
        "tip": 5.00,
        "taxes": [{"tax_name": "Sales Tax", "tax_amount": 2.10}],
        "is_tax_exempt": False,
        "order_total": 31.09,
        "balance_owing": 0.00,
        "notes": "Ring the doorbell",
        "customer": {
            "first_name": "Sarah",
            "last_name": "Connor",
            "company": "",
            "phone": "5559876543",
            "ext": "",
            "email": "sarah@example.com",
        },
        "delivery_address": {
            "street": "123 Main St",
            "cross_streets": "Main & 3rd",
            "suite": "Apt 4B",
            "buz": "",
            "city": "New York",
            "state": "NY",
            "zip": "10001",
        },
        "delivery_provider": None,
        "payments": [
            {
                "type": "cash",
                "amount": 31.09,
                "card_number": "",
                "card_holder": "",
                "auth_code": "",
                "transaction_id": "",
                "token": "",
            }
        ],
        "items": [
            {
                "name": "Pepperoni Pizza",
                "size_id": 3,
                "size_name": "Large",
                "quantity": 1,
                "price": 20.00,
                "plu": "PZ200",
                "who": "Kitchen",
                "group_id": "pizza",
                "notes": "Well done",
                "modifiers": [
                    {
                        "side": "whole",
                        "name": "Extra Cheese",
                        "quantity": 1,
                        "plu": "MOD01",
                        "price": 2.00,
                        "action": "add",
                    }
                ],
            }
        ],
        "coupons": [],
    },
    "tax_exempt_corporate_order": {
        "tVer": "1.0",
        "order_id": 1003,
        "store_id": 90002,
        "vendor_store_id": "BRY-002",
        "store_name": "Brygid Corporate",
        "service_type": "pickup",
        "submitted_date": "2026-02-07T12:30:00Z",
        "print_date": "2026-02-07T12:31:00Z",
        "deferred_date": "",
        "misc_charges": [],
        "tip": 0.00,
        "taxes": [],
        "is_tax_exempt": True,
        "order_total": 120.00,
        "balance_owing": 0.00,
        "notes": "Company lunch order",
        "customer": {
            "first_name": "Emily",
            "last_name": "Watson",
            "company": "TechCorp Inc.",
            "phone": "5553332222",
            "ext": "101",
            "email": "emily@techcorp.com",
        },
        "delivery_address": None,
        "delivery_provider": None,
        "payments": [
            {
                "type": "invoice",
                "amount": 120.00,
                "card_number": "",
                "card_holder": "",
                "auth_code": "",
                "transaction_id": "INV-9001",
                "token": "",
            }
        ],
        "items": [
            {
                "name": "Veggie Pizza",
                "size_id": 3,
                "size_name": "Large",
                "quantity": 5,
                "price": 24.00,
                "plu": "PZ300",
                "who": "Kitchen",
                "group_id": "pizza",
                "notes": "",
                "modifiers": [],
            }
        ],
        "coupons": [],
    },
    "third_party_delivery_order": {
        "tVer": "1.0",
        "order_id": 1004,
        "store_id": 90001,
        "vendor_store_id": "BRY-001",
        "store_name": "Brygid Pizza",
        "service_type": "delivery",
        "submitted_date": "2026-02-07T13:00:00Z",
        "print_date": "2026-02-07T13:01:00Z",
        "deferred_date": "",
        "misc_charges": [],
        "tip": 0.00,
        "taxes": [{"tax_name": "Sales Tax", "tax_amount": 1.25}],
        "is_tax_exempt": False,
        "order_total": 16.25,
        "balance_owing": 0.00,
        "notes": "",
        "customer": {
            "first_name": "Mike",
            "last_name": "Brown",
            "company": "",
            "phone": "5556667777",
            "ext": "",
            "email": "mike@example.com",
        },
        "delivery_address": {
            "street": "45 Market St",
            "cross_streets": "",
            "suite": "",
            "buz": "12",
            "city": "San Francisco",
            "state": "CA",
            "zip": "94103",
        },
        "delivery_provider": {
            "provider_name": "DoorDash",
            "status": "assigned",
            "delivery_id": "DD-7890",
            "tracking_url": "https://doordash.com/track/DD-7890",
            "pickup_date": "2026-02-07T13:15:00Z",
        },
        "payments": [
            {
                "type": "third_party",
                "amount": 16.25,
                "card_number": "",
                "card_holder": "",
                "auth_code": "",
                "transaction_id": "DDPAY123",
                "token": "",
            }
        ],
        "items": [
            {
                "name": "Cheese Pizza",
                "size_id": 1,
                "size_name": "Small",
                "quantity": 1,
                "price": 15.00,
                "plu": "PZ101",
                "who": "Kitchen",
                "group_id": "pizza",
                "notes": "",
                "modifiers": [],
            }
        ],
        "coupons": [],
    },
    "coupon_and_partial_payment": {
        "tVer": "1.0",
        "order_id": 1005,
        "store_id": 90001,
        "vendor_store_id": "BRY-001",
        "store_name": "Brygid Pizza",
        "service_type": "pickup",
        "submitted_date": "2026-02-07T14:00:00Z",
        "print_date": "2026-02-07T14:01:00Z",
        "deferred_date": "",
        "misc_charges": [],
        "tip": 3.00,
        "taxes": [{"tax_name": "Sales Tax", "tax_amount": 1.50}],
        "is_tax_exempt": False,
        "order_total": 20.50,
        "balance_owing": 5.50,
        "notes": "Customer will pay rest on pickup",
        "customer": {
            "first_name": "Alex",
            "last_name": "Kim",
            "company": "",
            "phone": "5558889999",
            "ext": "",
            "email": "alex@example.com",
        },
        "delivery_address": None,
        "delivery_provider": None,
        "payments": [
            {
                "type": "card",
                "amount": 15.00,
                "card_number": "**** **** **** 1111",
                "card_holder": "Alex Kim",
                "auth_code": "AUTH555",
                "transaction_id": "TXN555",
                "token": "tok_xyz555",
            }
        ],
        "items": [
            {
                "name": "BBQ Chicken Pizza",
                "size_id": 2,
                "size_name": "Medium",
                "quantity": 1,
                "price": 18.00,
                "plu": "PZ400",
                "who": "Kitchen",
                "group_id": "pizza",
                "notes": "",
                "modifiers": [],
            }
        ],
        "coupons": [
            {
                "serial": "SAVE5",
                "plu": "CPN5",
                "name": "$5 Off",
                "value": 5.00,
                "group_id": "promo",
            }
        ],
    },
}
