# elasticmq.conf
# quiccpos/elasticmq.conf
include classpath("application.conf")

node-address {
    protocol = http
    host = "*"
    port = 9324
    context-path = ""
}
rest-sqs {
    enabled = true
    bind-port = 9324
    bind-hostname = "0.0.0.0"
    sqs-limits = strict
}

queues {
    dev-ingest {
        defaultVisibilityTimeout = 30 seconds
        receiveMessageWait = 5 seconds
        fifo = false
    }
    dev-ingest-dlq {
        defaultVisibilityTimeout = 30 seconds
    }
    # add whatever quiccpos queues you have
}
