// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package models

import (
	"context"
)

// iteratorForCreateCoupon implements pgx.CopyFromSource.
type iteratorForCreateCoupon struct {
	rows                 []CreateCouponParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateCoupon) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateCoupon) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Serial,
		r.rows[0].Plu,
		r.rows[0].Name,
		r.rows[0].Value,
		r.rows[0].Groupid,
		r.rows[0].Orderid,
	}, nil
}

func (r iteratorForCreateCoupon) Err() error {
	return nil
}

func (q *Queries) CreateCoupon(ctx context.Context, arg []CreateCouponParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"coupons"}, []string{"serial", "plu", "name", "value", "groupid", "orderid"}, &iteratorForCreateCoupon{rows: arg})
}

// iteratorForCreateItem implements pgx.CopyFromSource.
type iteratorForCreateItem struct {
	rows                 []CreateItemParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateItem) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateItem) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Name,
		r.rows[0].Sizeid,
		r.rows[0].Sizename,
		r.rows[0].Quantity,
		r.rows[0].Price,
		r.rows[0].Plu,
		r.rows[0].Who,
		r.rows[0].Groupid,
		r.rows[0].Notes,
		r.rows[0].Orderid,
	}, nil
}

func (r iteratorForCreateItem) Err() error {
	return nil
}

func (q *Queries) CreateItem(ctx context.Context, arg []CreateItemParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"items"}, []string{"name", "sizeid", "sizename", "quantity", "price", "plu", "who", "groupid", "notes", "orderid"}, &iteratorForCreateItem{rows: arg})
}

// iteratorForCreateMiscCharge implements pgx.CopyFromSource.
type iteratorForCreateMiscCharge struct {
	rows                 []CreateMiscChargeParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateMiscCharge) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateMiscCharge) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Miscchargename,
		r.rows[0].Miscchargedesc,
		r.rows[0].Miscchargeamount,
		r.rows[0].Orderid,
	}, nil
}

func (r iteratorForCreateMiscCharge) Err() error {
	return nil
}

func (q *Queries) CreateMiscCharge(ctx context.Context, arg []CreateMiscChargeParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"misc_charges"}, []string{"miscchargename", "miscchargedesc", "miscchargeamount", "orderid"}, &iteratorForCreateMiscCharge{rows: arg})
}

// iteratorForCreateModifier implements pgx.CopyFromSource.
type iteratorForCreateModifier struct {
	rows                 []CreateModifierParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateModifier) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateModifier) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Side,
		r.rows[0].Name,
		r.rows[0].Quantity,
		r.rows[0].Plu,
		r.rows[0].Price,
		r.rows[0].Action,
		r.rows[0].Itemid,
	}, nil
}

func (r iteratorForCreateModifier) Err() error {
	return nil
}

func (q *Queries) CreateModifier(ctx context.Context, arg []CreateModifierParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"modifiers"}, []string{"side", "name", "quantity", "plu", "price", "action", "itemid"}, &iteratorForCreateModifier{rows: arg})
}

// iteratorForCreatePayment implements pgx.CopyFromSource.
type iteratorForCreatePayment struct {
	rows                 []CreatePaymentParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreatePayment) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreatePayment) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Paymenttype,
		r.rows[0].Amount,
		r.rows[0].Cardnumber,
		r.rows[0].Cardholder,
		r.rows[0].Authcode,
		r.rows[0].Transactionid,
		r.rows[0].Token,
		r.rows[0].Orderid,
	}, nil
}

func (r iteratorForCreatePayment) Err() error {
	return nil
}

func (q *Queries) CreatePayment(ctx context.Context, arg []CreatePaymentParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"payments"}, []string{"paymenttype", "amount", "cardnumber", "cardholder", "authcode", "transactionid", "token", "orderid"}, &iteratorForCreatePayment{rows: arg})
}

// iteratorForCreateTax implements pgx.CopyFromSource.
type iteratorForCreateTax struct {
	rows                 []CreateTaxParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateTax) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateTax) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Taxname,
		r.rows[0].Taxamount,
		r.rows[0].Orderid,
	}, nil
}

func (r iteratorForCreateTax) Err() error {
	return nil
}

func (q *Queries) CreateTax(ctx context.Context, arg []CreateTaxParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"taxes"}, []string{"taxname", "taxamount", "orderid"}, &iteratorForCreateTax{rows: arg})
}
