// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package models

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthKey struct {
	ID  int32  `json:"id"`
	Key string `json:"key"`
}

type Coupon struct {
	ID      int32         `json:"id"`
	Serial  pgtype.Text   `json:"serial"`
	Plu     pgtype.Text   `json:"plu"`
	Name    pgtype.Text   `json:"name"`
	Value   pgtype.Float4 `json:"value"`
	Groupid pgtype.Text   `json:"groupid"`
	Orderid pgtype.Int4   `json:"orderid"`
}

type Customer struct {
	ID        int32       `json:"id"`
	Firstname pgtype.Text `json:"firstname"`
	Lastname  pgtype.Text `json:"lastname"`
	Company   pgtype.Text `json:"company"`
	Phone     pgtype.Text `json:"phone"`
	Ext       pgtype.Text `json:"ext"`
	Email     pgtype.Text `json:"email"`
}

type DeliveryAddress struct {
	ID           int32       `json:"id"`
	Street       pgtype.Text `json:"street"`
	Crossstreets pgtype.Text `json:"crossstreets"`
	Suite        pgtype.Text `json:"suite"`
	Buz          pgtype.Text `json:"buz"`
	City         pgtype.Text `json:"city"`
	State        pgtype.Text `json:"state"`
	Zip          pgtype.Text `json:"zip"`
}

type DeliveryProvider struct {
	ID           int32       `json:"id"`
	Providername pgtype.Text `json:"providername"`
	Status       pgtype.Text `json:"status"`
	Deliveryid   pgtype.Text `json:"deliveryid"`
	Trackingurl  pgtype.Text `json:"trackingurl"`
	Pickupdate   pgtype.Text `json:"pickupdate"`
}

type Item struct {
	ID       int32         `json:"id"`
	Name     pgtype.Text   `json:"name"`
	Sizeid   pgtype.Int4   `json:"sizeid"`
	Sizename pgtype.Text   `json:"sizename"`
	Quantity pgtype.Int4   `json:"quantity"`
	Price    pgtype.Float4 `json:"price"`
	Plu      pgtype.Text   `json:"plu"`
	Who      pgtype.Text   `json:"who"`
	Groupid  pgtype.Text   `json:"groupid"`
	Notes    pgtype.Text   `json:"notes"`
	Orderid  pgtype.Int4   `json:"orderid"`
}

type MiscCharge struct {
	ID               int32         `json:"id"`
	Miscchargename   pgtype.Text   `json:"miscchargename"`
	Miscchargedesc   pgtype.Text   `json:"miscchargedesc"`
	Miscchargeamount pgtype.Float4 `json:"miscchargeamount"`
	Orderid          pgtype.Int4   `json:"orderid"`
}

type Modifier struct {
	ID       int32         `json:"id"`
	Side     pgtype.Text   `json:"side"`
	Name     pgtype.Text   `json:"name"`
	Quantity pgtype.Int4   `json:"quantity"`
	Plu      pgtype.Text   `json:"plu"`
	Price    pgtype.Float4 `json:"price"`
	Action   pgtype.Text   `json:"action"`
	Itemid   pgtype.Int4   `json:"itemid"`
}

type Order struct {
	Tver             pgtype.Int4   `json:"tver"`
	Orderid          int32         `json:"orderid"`
	Storeid          pgtype.Int4   `json:"storeid"`
	Vendorstoreid    pgtype.Text   `json:"vendorstoreid"`
	Storename        pgtype.Text   `json:"storename"`
	Servicetype      pgtype.Text   `json:"servicetype"`
	Submitteddate    pgtype.Text   `json:"submitteddate"`
	Printdate        pgtype.Text   `json:"printdate"`
	Deferreddate     pgtype.Text   `json:"deferreddate"`
	Istaxexempt      pgtype.Bool   `json:"istaxexempt"`
	Ordertotal       pgtype.Float4 `json:"ordertotal"`
	Balanceowing     pgtype.Float4 `json:"balanceowing"`
	Notes            pgtype.Text   `json:"notes"`
	Tip              pgtype.Float4 `json:"tip"`
	Customer         pgtype.Int4   `json:"customer"`
	Deliveryaddress  pgtype.Int4   `json:"deliveryaddress"`
	Deliveryprovider pgtype.Int4   `json:"deliveryprovider"`
}

type Payment struct {
	ID            int32         `json:"id"`
	Paymenttype   pgtype.Text   `json:"paymenttype"`
	Amount        pgtype.Float4 `json:"amount"`
	Cardnumber    pgtype.Text   `json:"cardnumber"`
	Cardholder    pgtype.Text   `json:"cardholder"`
	Authcode      pgtype.Text   `json:"authcode"`
	Transactionid pgtype.Text   `json:"transactionid"`
	Token         pgtype.Text   `json:"token"`
	Orderid       pgtype.Int4   `json:"orderid"`
}

type Tax struct {
	ID        int32         `json:"id"`
	Taxname   pgtype.Text   `json:"taxname"`
	Taxamount pgtype.Float4 `json:"taxamount"`
	Orderid   pgtype.Int4   `json:"orderid"`
}
