// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package models

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateCoupon(ctx context.Context, arg []CreateCouponParams) (int64, error)
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) (int32, error)
	CreateDeliveryAddress(ctx context.Context, arg CreateDeliveryAddressParams) (int32, error)
	CreateDeliveryProvider(ctx context.Context, arg CreateDeliveryProviderParams) (int32, error)
	CreateItem(ctx context.Context, arg []CreateItemParams) (int64, error)
	CreateMiscCharge(ctx context.Context, arg []CreateMiscChargeParams) (int64, error)
	CreateModifier(ctx context.Context, arg []CreateModifierParams) (int64, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (int32, error)
	CreatePayment(ctx context.Context, arg []CreatePaymentParams) (int64, error)
	CreateSingleItem(ctx context.Context, arg CreateSingleItemParams) (int32, error)
	CreateTax(ctx context.Context, arg []CreateTaxParams) (int64, error)
	GetAllOrders(ctx context.Context) ([]Order, error)
	GetCouponsByOrderID(ctx context.Context, orderid pgtype.Int4) ([]Coupon, error)
	GetCustomerByID(ctx context.Context, id int32) (Customer, error)
	GetDeliveryAddressByID(ctx context.Context, id int32) (DeliveryAddress, error)
	GetDeliveryProviderByID(ctx context.Context, id int32) (DeliveryProvider, error)
	GetItemsByOrderID(ctx context.Context, orderid pgtype.Int4) ([]Item, error)
	GetLatest(ctx context.Context) (Order, error)
	GetMiscChargesByOrderID(ctx context.Context, orderid pgtype.Int4) ([]MiscCharge, error)
	GetModifiersByItemID(ctx context.Context, itemid pgtype.Int4) ([]Modifier, error)
	GetOrderByID(ctx context.Context, orderid int32) (Order, error)
	GetOrdersPage(ctx context.Context, arg GetOrdersPageParams) ([]Order, error)
	GetPaymentsByOrderID(ctx context.Context, orderid pgtype.Int4) ([]Payment, error)
	GetTaxesByOrderID(ctx context.Context, orderid pgtype.Int4) ([]Tax, error)
}

var _ Querier = (*Queries)(nil)
