// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package models

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type CreateCouponParams struct {
	Serial  pgtype.Text   `json:"serial"`
	Plu     pgtype.Text   `json:"plu"`
	Name    pgtype.Text   `json:"name"`
	Value   pgtype.Float4 `json:"value"`
	Groupid pgtype.Text   `json:"groupid"`
	Orderid pgtype.Int4   `json:"orderid"`
}

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO customers(FirstName, LastName, Company, Phone, Ext, Email)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (Phone) DO UPDATE SET
    FirstName = EXCLUDED.FirstName,
    LastName  = EXCLUDED.LastName,
    Company   = EXCLUDED.Company,
    Ext       = EXCLUDED.Ext,
    Email     = EXCLUDED.Email
RETURNING id
`

type CreateCustomerParams struct {
	Firstname pgtype.Text `json:"firstname"`
	Lastname  pgtype.Text `json:"lastname"`
	Company   pgtype.Text `json:"company"`
	Phone     pgtype.Text `json:"phone"`
	Ext       pgtype.Text `json:"ext"`
	Email     pgtype.Text `json:"email"`
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (int32, error) {
	row := q.db.QueryRow(ctx, createCustomer,
		arg.Firstname,
		arg.Lastname,
		arg.Company,
		arg.Phone,
		arg.Ext,
		arg.Email,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const createDeliveryAddress = `-- name: CreateDeliveryAddress :one
INSERT INTO delivery_addresses(Street, CrossStreets, Suite, Buz, City, State, Zip)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id
`

type CreateDeliveryAddressParams struct {
	Street       pgtype.Text `json:"street"`
	Crossstreets pgtype.Text `json:"crossstreets"`
	Suite        pgtype.Text `json:"suite"`
	Buz          pgtype.Text `json:"buz"`
	City         pgtype.Text `json:"city"`
	State        pgtype.Text `json:"state"`
	Zip          pgtype.Text `json:"zip"`
}

func (q *Queries) CreateDeliveryAddress(ctx context.Context, arg CreateDeliveryAddressParams) (int32, error) {
	row := q.db.QueryRow(ctx, createDeliveryAddress,
		arg.Street,
		arg.Crossstreets,
		arg.Suite,
		arg.Buz,
		arg.City,
		arg.State,
		arg.Zip,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const createDeliveryProvider = `-- name: CreateDeliveryProvider :one
INSERT INTO delivery_providers(ProviderName, Status, DeliveryID, TrackingURL, PickupDate)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (DeliveryID) DO UPDATE SET
    Status      = EXCLUDED.Status,
    TrackingURL = EXCLUDED.TrackingURL,
    PickupDate  = EXCLUDED.PickupDate
RETURNING id
`

type CreateDeliveryProviderParams struct {
	Providername pgtype.Text `json:"providername"`
	Status       pgtype.Text `json:"status"`
	Deliveryid   pgtype.Text `json:"deliveryid"`
	Trackingurl  pgtype.Text `json:"trackingurl"`
	Pickupdate   pgtype.Text `json:"pickupdate"`
}

func (q *Queries) CreateDeliveryProvider(ctx context.Context, arg CreateDeliveryProviderParams) (int32, error) {
	row := q.db.QueryRow(ctx, createDeliveryProvider,
		arg.Providername,
		arg.Status,
		arg.Deliveryid,
		arg.Trackingurl,
		arg.Pickupdate,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

type CreateItemParams struct {
	Name     pgtype.Text   `json:"name"`
	Sizeid   pgtype.Int4   `json:"sizeid"`
	Sizename pgtype.Text   `json:"sizename"`
	Quantity pgtype.Int4   `json:"quantity"`
	Price    pgtype.Float4 `json:"price"`
	Plu      pgtype.Text   `json:"plu"`
	Who      pgtype.Text   `json:"who"`
	Groupid  pgtype.Text   `json:"groupid"`
	Notes    pgtype.Text   `json:"notes"`
	Orderid  pgtype.Int4   `json:"orderid"`
}

type CreateMiscChargeParams struct {
	Miscchargename   pgtype.Text   `json:"miscchargename"`
	Miscchargedesc   pgtype.Text   `json:"miscchargedesc"`
	Miscchargeamount pgtype.Float4 `json:"miscchargeamount"`
	Orderid          pgtype.Int4   `json:"orderid"`
}

type CreateModifierParams struct {
	Side     pgtype.Text   `json:"side"`
	Name     pgtype.Text   `json:"name"`
	Quantity pgtype.Int4   `json:"quantity"`
	Plu      pgtype.Text   `json:"plu"`
	Price    pgtype.Float4 `json:"price"`
	Action   pgtype.Text   `json:"action"`
	Itemid   pgtype.Int4   `json:"itemid"`
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders(TVer, OrderID, StoreID, VendorStoreID, StoreName, ServiceType, SubmittedDate, PrintDate, DeferredDate, IsTaxExempt, OrderTotal, BalanceOwing, Notes, Tip, Customer, DeliveryAddress, DeliveryProvider)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17)
ON CONFLICT (OrderID) DO NOTHING
RETURNING OrderID
`

type CreateOrderParams struct {
	Tver             pgtype.Int4   `json:"tver"`
	Orderid          int32         `json:"orderid"`
	Storeid          pgtype.Int4   `json:"storeid"`
	Vendorstoreid    pgtype.Text   `json:"vendorstoreid"`
	Storename        pgtype.Text   `json:"storename"`
	Servicetype      pgtype.Text   `json:"servicetype"`
	Submitteddate    pgtype.Text   `json:"submitteddate"`
	Printdate        pgtype.Text   `json:"printdate"`
	Deferreddate     pgtype.Text   `json:"deferreddate"`
	Istaxexempt      pgtype.Bool   `json:"istaxexempt"`
	Ordertotal       pgtype.Float4 `json:"ordertotal"`
	Balanceowing     pgtype.Float4 `json:"balanceowing"`
	Notes            pgtype.Text   `json:"notes"`
	Tip              pgtype.Float4 `json:"tip"`
	Customer         pgtype.Int4   `json:"customer"`
	Deliveryaddress  pgtype.Int4   `json:"deliveryaddress"`
	Deliveryprovider pgtype.Int4   `json:"deliveryprovider"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (int32, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.Tver,
		arg.Orderid,
		arg.Storeid,
		arg.Vendorstoreid,
		arg.Storename,
		arg.Servicetype,
		arg.Submitteddate,
		arg.Printdate,
		arg.Deferreddate,
		arg.Istaxexempt,
		arg.Ordertotal,
		arg.Balanceowing,
		arg.Notes,
		arg.Tip,
		arg.Customer,
		arg.Deliveryaddress,
		arg.Deliveryprovider,
	)
	var orderid int32
	err := row.Scan(&orderid)
	return orderid, err
}

type CreatePaymentParams struct {
	Paymenttype   pgtype.Text   `json:"paymenttype"`
	Amount        pgtype.Float4 `json:"amount"`
	Cardnumber    pgtype.Text   `json:"cardnumber"`
	Cardholder    pgtype.Text   `json:"cardholder"`
	Authcode      pgtype.Text   `json:"authcode"`
	Transactionid pgtype.Text   `json:"transactionid"`
	Token         pgtype.Text   `json:"token"`
	Orderid       pgtype.Int4   `json:"orderid"`
}

const createSingleItem = `-- name: CreateSingleItem :one
INSERT INTO items(Name, SizeID, SizeName, Quantity, Price, PLU, Who, GroupID, Notes, OrderID)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id
`

type CreateSingleItemParams struct {
	Name     pgtype.Text   `json:"name"`
	Sizeid   pgtype.Int4   `json:"sizeid"`
	Sizename pgtype.Text   `json:"sizename"`
	Quantity pgtype.Int4   `json:"quantity"`
	Price    pgtype.Float4 `json:"price"`
	Plu      pgtype.Text   `json:"plu"`
	Who      pgtype.Text   `json:"who"`
	Groupid  pgtype.Text   `json:"groupid"`
	Notes    pgtype.Text   `json:"notes"`
	Orderid  pgtype.Int4   `json:"orderid"`
}

func (q *Queries) CreateSingleItem(ctx context.Context, arg CreateSingleItemParams) (int32, error) {
	row := q.db.QueryRow(ctx, createSingleItem,
		arg.Name,
		arg.Sizeid,
		arg.Sizename,
		arg.Quantity,
		arg.Price,
		arg.Plu,
		arg.Who,
		arg.Groupid,
		arg.Notes,
		arg.Orderid,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

type CreateTaxParams struct {
	Taxname   pgtype.Text   `json:"taxname"`
	Taxamount pgtype.Float4 `json:"taxamount"`
	Orderid   pgtype.Int4   `json:"orderid"`
}

const getAllOrders = `-- name: GetAllOrders :many
SELECT tver, orderid, storeid, vendorstoreid, storename, servicetype, submitteddate, printdate, deferreddate, istaxexempt, ordertotal, balanceowing, notes, tip, customer, deliveryaddress, deliveryprovider FROM orders
`

func (q *Queries) GetAllOrders(ctx context.Context) ([]Order, error) {
	rows, err := q.db.Query(ctx, getAllOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.Tver,
			&i.Orderid,
			&i.Storeid,
			&i.Vendorstoreid,
			&i.Storename,
			&i.Servicetype,
			&i.Submitteddate,
			&i.Printdate,
			&i.Deferreddate,
			&i.Istaxexempt,
			&i.Ordertotal,
			&i.Balanceowing,
			&i.Notes,
			&i.Tip,
			&i.Customer,
			&i.Deliveryaddress,
			&i.Deliveryprovider,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAuthKey = `-- name: GetAuthKey :one
SELECT key FROM auth_keys WHERE id = 1
`

func (q *Queries) GetAuthKey(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, getAuthKey)
	var key string
	err := row.Scan(&key)
	return key, err
}

const getCouponsByOrderID = `-- name: GetCouponsByOrderID :many
SELECT id, serial, plu, name, value, groupid, orderid FROM coupons WHERE OrderID = $1
`

func (q *Queries) GetCouponsByOrderID(ctx context.Context, orderid pgtype.Int4) ([]Coupon, error) {
	rows, err := q.db.Query(ctx, getCouponsByOrderID, orderid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Coupon
	for rows.Next() {
		var i Coupon
		if err := rows.Scan(
			&i.ID,
			&i.Serial,
			&i.Plu,
			&i.Name,
			&i.Value,
			&i.Groupid,
			&i.Orderid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCustomerByID = `-- name: GetCustomerByID :one
SELECT id, firstname, lastname, company, phone, ext, email FROM customers WHERE id = $1
`

func (q *Queries) GetCustomerByID(ctx context.Context, id int32) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerByID, id)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Firstname,
		&i.Lastname,
		&i.Company,
		&i.Phone,
		&i.Ext,
		&i.Email,
	)
	return i, err
}

const getDeliveryAddressByID = `-- name: GetDeliveryAddressByID :one
SELECT id, street, crossstreets, suite, buz, city, state, zip FROM delivery_addresses WHERE id = $1
`

func (q *Queries) GetDeliveryAddressByID(ctx context.Context, id int32) (DeliveryAddress, error) {
	row := q.db.QueryRow(ctx, getDeliveryAddressByID, id)
	var i DeliveryAddress
	err := row.Scan(
		&i.ID,
		&i.Street,
		&i.Crossstreets,
		&i.Suite,
		&i.Buz,
		&i.City,
		&i.State,
		&i.Zip,
	)
	return i, err
}

const getDeliveryProviderByID = `-- name: GetDeliveryProviderByID :one
SELECT id, providername, status, deliveryid, trackingurl, pickupdate FROM delivery_providers WHERE id = $1
`

func (q *Queries) GetDeliveryProviderByID(ctx context.Context, id int32) (DeliveryProvider, error) {
	row := q.db.QueryRow(ctx, getDeliveryProviderByID, id)
	var i DeliveryProvider
	err := row.Scan(
		&i.ID,
		&i.Providername,
		&i.Status,
		&i.Deliveryid,
		&i.Trackingurl,
		&i.Pickupdate,
	)
	return i, err
}

const getItemsByOrderID = `-- name: GetItemsByOrderID :many
SELECT id, name, sizeid, sizename, quantity, price, plu, who, groupid, notes, orderid FROM items WHERE OrderID = $1
`

func (q *Queries) GetItemsByOrderID(ctx context.Context, orderid pgtype.Int4) ([]Item, error) {
	rows, err := q.db.Query(ctx, getItemsByOrderID, orderid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Sizeid,
			&i.Sizename,
			&i.Quantity,
			&i.Price,
			&i.Plu,
			&i.Who,
			&i.Groupid,
			&i.Notes,
			&i.Orderid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatest = `-- name: GetLatest :one
Select tver, orderid, storeid, vendorstoreid, storename, servicetype, submitteddate, printdate, deferreddate, istaxexempt, ordertotal, balanceowing, notes, tip, customer, deliveryaddress, deliveryprovider FROM orders ORDER BY OrderID DESC LIMIT 1
`

func (q *Queries) GetLatest(ctx context.Context) (Order, error) {
	row := q.db.QueryRow(ctx, getLatest)
	var i Order
	err := row.Scan(
		&i.Tver,
		&i.Orderid,
		&i.Storeid,
		&i.Vendorstoreid,
		&i.Storename,
		&i.Servicetype,
		&i.Submitteddate,
		&i.Printdate,
		&i.Deferreddate,
		&i.Istaxexempt,
		&i.Ordertotal,
		&i.Balanceowing,
		&i.Notes,
		&i.Tip,
		&i.Customer,
		&i.Deliveryaddress,
		&i.Deliveryprovider,
	)
	return i, err
}

const getMiscChargesByOrderID = `-- name: GetMiscChargesByOrderID :many
SELECT id, miscchargename, miscchargedesc, miscchargeamount, orderid FROM misc_charges WHERE OrderID = $1
`

func (q *Queries) GetMiscChargesByOrderID(ctx context.Context, orderid pgtype.Int4) ([]MiscCharge, error) {
	rows, err := q.db.Query(ctx, getMiscChargesByOrderID, orderid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MiscCharge
	for rows.Next() {
		var i MiscCharge
		if err := rows.Scan(
			&i.ID,
			&i.Miscchargename,
			&i.Miscchargedesc,
			&i.Miscchargeamount,
			&i.Orderid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getModifiersByItemID = `-- name: GetModifiersByItemID :many
SELECT id, side, name, quantity, plu, price, action, itemid FROM modifiers WHERE ItemID = $1
`

func (q *Queries) GetModifiersByItemID(ctx context.Context, itemid pgtype.Int4) ([]Modifier, error) {
	rows, err := q.db.Query(ctx, getModifiersByItemID, itemid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Modifier
	for rows.Next() {
		var i Modifier
		if err := rows.Scan(
			&i.ID,
			&i.Side,
			&i.Name,
			&i.Quantity,
			&i.Plu,
			&i.Price,
			&i.Action,
			&i.Itemid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT tver, orderid, storeid, vendorstoreid, storename, servicetype, submitteddate, printdate, deferreddate, istaxexempt, ordertotal, balanceowing, notes, tip, customer, deliveryaddress, deliveryprovider FROM orders WHERE OrderID = $1
`

func (q *Queries) GetOrderByID(ctx context.Context, orderid int32) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByID, orderid)
	var i Order
	err := row.Scan(
		&i.Tver,
		&i.Orderid,
		&i.Storeid,
		&i.Vendorstoreid,
		&i.Storename,
		&i.Servicetype,
		&i.Submitteddate,
		&i.Printdate,
		&i.Deferreddate,
		&i.Istaxexempt,
		&i.Ordertotal,
		&i.Balanceowing,
		&i.Notes,
		&i.Tip,
		&i.Customer,
		&i.Deliveryaddress,
		&i.Deliveryprovider,
	)
	return i, err
}

const getOrdersPage = `-- name: GetOrdersPage :many
SELECT tver, orderid, storeid, vendorstoreid, storename, servicetype, submitteddate, printdate, deferreddate, istaxexempt, ordertotal, balanceowing, notes, tip, customer, deliveryaddress, deliveryprovider FROM orders ORDER BY OrderID DESC LIMIT $1 OFFSET $2
`

type GetOrdersPageParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetOrdersPage(ctx context.Context, arg GetOrdersPageParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, getOrdersPage, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.Tver,
			&i.Orderid,
			&i.Storeid,
			&i.Vendorstoreid,
			&i.Storename,
			&i.Servicetype,
			&i.Submitteddate,
			&i.Printdate,
			&i.Deferreddate,
			&i.Istaxexempt,
			&i.Ordertotal,
			&i.Balanceowing,
			&i.Notes,
			&i.Tip,
			&i.Customer,
			&i.Deliveryaddress,
			&i.Deliveryprovider,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPaymentsByOrderID = `-- name: GetPaymentsByOrderID :many
SELECT id, paymenttype, amount, cardnumber, cardholder, authcode, transactionid, token, orderid FROM payments WHERE OrderID = $1
`

func (q *Queries) GetPaymentsByOrderID(ctx context.Context, orderid pgtype.Int4) ([]Payment, error) {
	rows, err := q.db.Query(ctx, getPaymentsByOrderID, orderid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.Paymenttype,
			&i.Amount,
			&i.Cardnumber,
			&i.Cardholder,
			&i.Authcode,
			&i.Transactionid,
			&i.Token,
			&i.Orderid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaxesByOrderID = `-- name: GetTaxesByOrderID :many
SELECT id, taxname, taxamount, orderid FROM taxes WHERE OrderID = $1
`

func (q *Queries) GetTaxesByOrderID(ctx context.Context, orderid pgtype.Int4) ([]Tax, error) {
	rows, err := q.db.Query(ctx, getTaxesByOrderID, orderid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tax
	for rows.Next() {
		var i Tax
		if err := rows.Scan(
			&i.ID,
			&i.Taxname,
			&i.Taxamount,
			&i.Orderid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAuthKey = `-- name: SetAuthKey :exec
INSERT INTO auth_keys(id, key) VALUES (1, $1)
ON CONFLICT (id) DO UPDATE SET key = EXCLUDED.key
`

func (q *Queries) SetAuthKey(ctx context.Context, key string) error {
	_, err := q.db.Exec(ctx, setAuthKey, key)
	return err
}
